#!/usr/bin/env bash
set -euo pipefail

if [[ $# -lt 2 ]]; then
  echo "Usage: bash run_selected_tau_suite.sh <TAU_MAIN> <TAU_STRICT> [CASE_NAME]"
  exit 1
fi

TAU_MAIN="$1"
TAU_STRICT="$2"
CASE_NAME="${3:-case14}"

LOG_DIR="logs"
METRIC_DIR="metric/${CASE_NAME}"
MIXED_MAIN_DIR="${METRIC_DIR}/plots_mixed_timeline_compare_tau_main"
MIXED_STRICT_DIR="${METRIC_DIR}/plots_mixed_timeline_compare_tau_strict"
mkdir -p "${LOG_DIR}" "${MIXED_MAIN_DIR}" "${MIXED_STRICT_DIR}"

sanitize_tau() {
  local x="$1"
  python - <<PY
x=float("$x")
print(f"{x:.6f}")
PY
}

TAU_MAIN_TAG=$(sanitize_tau "$TAU_MAIN")
TAU_STRICT_TAG=$(sanitize_tau "$TAU_STRICT")

run_and_log() {
  local name="$1"
  shift
  echo "\n===== Running: ${name} ====="
  echo "Command: $*"
  "$@" 2>&1 | tee "${LOG_DIR}/${name}.log"
}

# 1) Clean full-run
run_and_log clean_baseline \
  python evaluation_event_trigger_clean.py \
  --tau_verify -1.0 --max_total_run -1 --stop_ddd_alarm_at -1

run_and_log clean_main \
  python evaluation_event_trigger_clean.py \
  --tau_verify "${TAU_MAIN}" --max_total_run -1 --stop_ddd_alarm_at -1

run_and_log clean_strict \
  python evaluation_event_trigger_clean.py \
  --tau_verify "${TAU_STRICT}" --max_total_run -1 --stop_ddd_alarm_at -1

# 2) Attack supporting (50 runs / group to stay consistent with current paper protocol)
run_and_log attack_main \
  python evaluation_event_trigger_attack_cli.py \
  --tau_verify "${TAU_MAIN}" --total_run 50

run_and_log attack_strict \
  python evaluation_event_trigger_attack_cli.py \
  --tau_verify "${TAU_STRICT}" --total_run 50

# 3) Mixed timeline with explicit outputs
BASELINE_MIXED="${METRIC_DIR}/metric_mixed_timeline_tau_-1.0.npy"
MAIN_MIXED="${METRIC_DIR}/metric_mixed_timeline_tau_${TAU_MAIN_TAG}.npy"
STRICT_MIXED="${METRIC_DIR}/metric_mixed_timeline_tau_${TAU_STRICT_TAG}.npy"

run_and_log mixed_baseline \
  python evaluation_mixed_timeline.py \
  --tau_verify -1.0 --output "${BASELINE_MIXED}"

run_and_log mixed_main \
  python evaluation_mixed_timeline.py \
  --tau_verify "${TAU_MAIN}" --output "${MAIN_MIXED}"

run_and_log mixed_strict \
  python evaluation_mixed_timeline.py \
  --tau_verify "${TAU_STRICT}" --output "${STRICT_MIXED}"

# 4) Paired comparisons
run_and_log compare_mixed_main \
  python compare_mixed_timeline.py \
  --baseline "${BASELINE_MIXED}" \
  --gated "${MAIN_MIXED}" \
  --output_dir "${MIXED_MAIN_DIR}"

run_and_log compare_mixed_strict \
  python compare_mixed_timeline.py \
  --baseline "${BASELINE_MIXED}" \
  --gated "${STRICT_MIXED}" \
  --output_dir "${MIXED_STRICT_DIR}"

# 5) Helpful pointers
cat <<MSG

===== Finished =====
Please inspect these files first:
1) Clean logs:
   ${LOG_DIR}/clean_main.log
   ${LOG_DIR}/clean_strict.log
2) Attack summaries generated by evaluation_event_trigger_attack_cli.py under:
   ${METRIC_DIR}/*.summary.txt
3) Mixed paired summaries:
   ${MIXED_MAIN_DIR}/mixed_timeline_compare_summary.txt
   ${MIXED_STRICT_DIR}/mixed_timeline_compare_summary.txt
MSG
